-- MySQL Script generated by MySQL Workbench
-- mar. 22 mai 2018 11:09:52 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CDFgeo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CDFgeo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CDFgeo` DEFAULT CHARACTER SET utf8 ;
USE `CDFgeo` ;

-- -----------------------------------------------------
-- Table `CDFgeo`.`chaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDFgeo`.`chaire` ;

CREATE TABLE IF NOT EXISTS `CDFgeo`.`chaire` (
  `chaire_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `chaire_intitule` TINYTEXT NOT NULL,
  `chaire_type` TINYTEXT NOT NULL,
  `chaire_debut` VARCHAR(4) NOT NULL,
  `chaire_fin` VARCHAR(4) NOT NULL,
  `chaire_precision` TEXT NULL,
  PRIMARY KEY (`chaire_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CDFgeo`.`lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDFgeo`.`lieu` ;

CREATE TABLE IF NOT EXISTS `CDFgeo`.`lieu` (
  `lieu_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `lieu_ville` TINYTEXT NOT NULL,
  `lieu_latville` FLOAT NOT NULL,
  `lieu_longville` FLOAT NOT NULL,
  `lieu_pays` TINYTEXT NOT NULL,
  `lieu_latpays` FLOAT NOT NULL,
  `lieu_longpays` FLOAT NOT NULL,
  PRIMARY KEY (`lieu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CDFgeo`.`personne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDFgeo`.`personne` ;

CREATE TABLE IF NOT EXISTS `CDFgeo`.`personne` (
  `personne_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `personne_prenom` TINYTEXT NOT NULL,
  `personne_nom` TINYTEXT NOT NULL,
  `personne_statut` TINYTEXT NOT NULL,
  `personne_naissance` VARCHAR(4) NULL,
  `personne_deces` VARCHAR(4) NULL,
  `personne_precision` TEXT NULL,
  `personne_liensexternes` TINYTEXT NULL,
  `chaire_chaire_id` SMALLINT NOT NULL,
  `lieu_lieu_id` SMALLINT NOT NULL,
  PRIMARY KEY (`personne_id`, `chaire_chaire_id`, `lieu_lieu_id`),
  INDEX `fk_personne_chaire_idx` (`chaire_chaire_id` ASC),
  INDEX `fk_personne_lieu1_idx` (`lieu_lieu_id` ASC),
  CONSTRAINT `fk_personne_chaire`
    FOREIGN KEY (`chaire_chaire_id`)
    REFERENCES `CDFgeo`.`chaire` (`chaire_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personne_lieu1`
    FOREIGN KEY (`lieu_lieu_id`)
    REFERENCES `CDFgeo`.`lieu` (`lieu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CDFgeo`.`date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDFgeo`.`date` ;

CREATE TABLE IF NOT EXISTS `CDFgeo`.`date` (
  `date_id` SMALLINT NOT NULL,
  `date_debut` VARCHAR(10) NULL,
  `date_fin` VARCHAR(10) NULL,
  `date_note` VARCHAR(45) NULL,
  PRIMARY KEY (`date_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CDFgeo`.`mission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDFgeo`.`mission` ;

CREATE TABLE IF NOT EXISTS `CDFgeo`.`mission` (
  `mission_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `mission_intitule` TINYTEXT NOT NULL,
  `mission_type` TINYTEXT NOT NULL,
  `mission_institution` TINYTEXT NULL,
  `mission_precision` TEXT NULL,
  `date_date_id` SMALLINT NOT NULL,
  `lieu_lieu_id` SMALLINT NOT NULL,
  PRIMARY KEY (`mission_id`, `date_date_id`, `lieu_lieu_id`),
  INDEX `fk_mission_date1_idx` (`date_date_id` ASC),
  INDEX `fk_mission_lieu1_idx` (`lieu_lieu_id` ASC),
  CONSTRAINT `fk_mission_date1`
    FOREIGN KEY (`date_date_id`)
    REFERENCES `CDFgeo`.`date` (`date_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mission_lieu1`
    FOREIGN KEY (`lieu_lieu_id`)
    REFERENCES `CDFgeo`.`lieu` (`lieu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
