-- MySQL Script generated by MySQL Workbench
-- jeu. 24 mai 2018 14:40:39 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CDFgeo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CDFgeo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CDFgeo` DEFAULT CHARACTER SET utf8 ;
USE `CDFgeo` ;

-- -----------------------------------------------------
-- Table `CDFgeo`.`chaire`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDFgeo`.`chaire` ;

CREATE TABLE IF NOT EXISTS `CDFgeo`.`chaire` (
  `chaire_id` SMALLINT NOT NULL,
  `chaire_intitule` TINYTEXT NOT NULL,
  `chaire_type` TINYTEXT NOT NULL,
  `chaire_debut` VARCHAR(4) NOT NULL,
  `chaire_fin` VARCHAR(4) NOT NULL,
  `chaire_precision` TEXT NULL,
  PRIMARY KEY (`chaire_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CDFgeo`.`personne`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDFgeo`.`personne` ;

CREATE TABLE IF NOT EXISTS `CDFgeo`.`personne` (
  `personne_id` SMALLINT NOT NULL,
  `personne_prenom` TINYTEXT NOT NULL,
  `personne_nom` TINYTEXT NOT NULL,
  `personne_statut` TINYTEXT NOT NULL,
  `personne_naissance` VARCHAR(4) NULL,
  `personne_deces` VARCHAR(4) NULL,
  `personne_precision` TEXT NULL,
  `personne_liensexternes` TINYTEXT NULL,
  `chaire_chaire_id` SMALLINT NULL,
  PRIMARY KEY (`personne_id`),
  INDEX `fk_personne_chaire_idx` (`chaire_chaire_id` ASC),
  CONSTRAINT `fk_personne_chaire`
    FOREIGN KEY (`chaire_chaire_id`)
    REFERENCES `CDFgeo`.`chaire` (`chaire_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CDFgeo`.`lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDFgeo`.`lieu` ;

CREATE TABLE IF NOT EXISTS `CDFgeo`.`lieu` (
  `lieu_id` SMALLINT NOT NULL,
  `lieu_ville` TINYTEXT NULL,
  `lieu_latville` FLOAT NULL,
  `lieu_longville` FLOAT NULL,
  `lieu_pays` TINYTEXT NOT NULL,
  `lieu_latpays` FLOAT NOT NULL,
  `lieu_longpays` FLOAT NOT NULL,
  PRIMARY KEY (`lieu_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CDFgeo`.`mission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDFgeo`.`mission` ;

CREATE TABLE IF NOT EXISTS `CDFgeo`.`mission` (
  `mission_id` SMALLINT NOT NULL,
  `mission_intitule` TINYTEXT NOT NULL,
  `mission_type` TINYTEXT NULL,
  `mission_institution` TINYTEXT NULL,
  `mission_date_debut` VARCHAR(10) NULL,
  `mission_date_fin` VARCHAR(10) NULL,
  `mission_dates` TINYTEXT NULL,
  `mission_precision` TEXT NULL,
  PRIMARY KEY (`mission_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CDFgeo`.`personne_mission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDFgeo`.`personne_mission` ;

CREATE TABLE IF NOT EXISTS `CDFgeo`.`personne_mission` (
  `personne_mission_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `personne_mission_personne_id` SMALLINT NOT NULL,
  `personne_mission_mission_id` SMALLINT NOT NULL,
  PRIMARY KEY (`personne_mission_id`),
  INDEX `fk_personne_mission_mission1_idx` (`personne_mission_mission_id` ASC),
  INDEX `fk_personne_mission_personne1_idx` (`personne_mission_personne_id` ASC),
  CONSTRAINT `fk_personne_mission_personne1`
    FOREIGN KEY (`personne_mission_personne_id`)
    REFERENCES `CDFgeo`.`personne` (`personne_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personne_mission_mission1`
    FOREIGN KEY (`personne_mission_mission_id`)
    REFERENCES `CDFgeo`.`mission` (`mission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CDFgeo`.`mission_lieu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CDFgeo`.`mission_lieu` ;

CREATE TABLE IF NOT EXISTS `CDFgeo`.`mission_lieu` (
  `mission_lieu_id` SMALLINT NOT NULL AUTO_INCREMENT,
  `mission_lieu_mission_id` SMALLINT NOT NULL,
  `mission_lieu_lieu_id` SMALLINT NOT NULL,
  PRIMARY KEY (`mission_lieu_id`),
  INDEX `fk_mission_lieu_lieu1_idx` (`mission_lieu_lieu_id` ASC),
  INDEX `fk_mission_lieu_mission1_idx` (`mission_lieu_mission_id` ASC),
  CONSTRAINT `fk_mission_lieu_mission1`
    FOREIGN KEY (`mission_lieu_mission_id`)
    REFERENCES `CDFgeo`.`mission` (`mission_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mission_lieu_lieu1`
    FOREIGN KEY (`mission_lieu_lieu_id`)
    REFERENCES `CDFgeo`.`lieu` (`lieu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
